package tc;

import java.util.*;


public class SimilarUserDetection
{
	public String haveSimilar(String[] handles)
	{
		String result = "Similar handles not found";
		for (int i = 0; i < handles.length; i++) {
			for (int j = i+1; j < handles.length; j++) {
				if(handles[i].length() != handles[j].length()) continue;;
				char[] a = handles[i].toCharArray();
				char[] b = handles[j].toCharArray();
				int k;
				for (k = 0; k < a.length; k++) {
					if(!isSame(a[k],b[k])) {
						break;
					}
				}
				if(k == a.length) return "Similar handles found";
			}
		}
		return result;
	}
	static boolean isSame(char x, char y) {
		Set<Character> group1 = new HashSet<Character>();
		Set<Character> group2 = new HashSet<Character>();
		group1.add('O');
		group1.add('0');

		group2.add('I');
		group2.add('l');
		group2.add('1');

		if(x == y) return true;
		else if(group1.contains(x) && group1.contains(y)) return true;
		else if(group2.contains(x) && group2.contains(y)) return true;
		else return false;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, String p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		SimilarUserDetection obj;
		String answer;
		obj = new SimilarUserDetection();
		long startTime = System.currentTimeMillis();
		answer = obj.haveSimilar(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p1 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p1);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		String p1;
		
		// ----- test 0 -----
		p0 = new String[]{"top","coder","TOPCODER","TOPC0DER"};
		p1 = "Similar handles found";
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"Topcoder","topcoder","t0pcoder","topcOder"};
		p1 = "Similar handles not found";
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"same","same","same","different"};
		p1 = "Similar handles found";
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"0123","0I23","0l23","O123","OI23","Ol23"};
		p1 = "Similar handles found";
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new String[]{"i23","123","456","789","000","o","O"};
		p1 = "Similar handles not found";
		all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
